### ISSUE TITLE
Not valid DKIM

### ISSUE THREAD

**Issue by hostbrook** [simonschaufi/laravel-dkim#12]
Hello,
I'm using your package. It works, the DKIM signature added, but both Outlook and mail-tester.com return the error: "Not valid DKIM". Can you please check? Have you tried to check the result DKIM with any services?
Thanks!

**Comment by simonschaufi** [comment]
Hello, foremost, which version are you using? I don't have an environment on Laravel 9 but @mrjose, who provided the Laravel 9 compatibility version said, that it works for him.

You need to make sure that the "selector" is correct, maybe that is your error? Follow the readme and then it should work.

**Comment by mrjose** [comment]
Hi @hostbrook just ran a test with mail-tester.com and Gmail, using laravel-dkim 2.0.0 and Laravel 9 - DKIM signature reporting as valid. No problems so far. 

I would recommend double checking you have your keys setup correctly, including the selector.

**Comment by hostbrook** [comment]
Hello again. I followed your package instructions and have double-checked all keys, it seems to me everything is correct:
The file `.env`:
```
DKIM_DOMAIN=hostbrook.com
DKIM_SELECTOR=220409
DKIM_IDENTITY=support@hostbrook.com
```
The file `private_key.txt` is in `storage/app/dkim/`, UTF-8 LF

DNS is added correctly (TXT record with name `220409._domainkey` ) - you can check on [dmarcanalyzer.com/dkim/dkim-checker](https://www.mail-tester.com/spf-dkim-check)

But still have an issue.

Gmail Original Message result:

```
Authentication-Results: mx.google.com;
spf=pass (google.com: domain of support@hostbrook.com designates 198.71.228.64 as permitted sender) smtp.mailfrom=support@hostbrook.com;
dkim=neutral (body hash did not verify) header.i=@hostbrook.com header.s=220409 header.b=e7+gyrXD
Received-SPF: pass (google.com: domain of support@hostbrook.com designates 198.71.228.64 as permitted sender) client-ip=198.71.228.64;

...

DKIM-Signature: v=1; q=dns/txt; a=rsa-sha256; bh=2s4zP7onDND0eE9/9K0cFNDTHGf9IpHPF6XzZ2HvIx4=; d=hostbrook.com; h=From: To: Subject: MIME-Version: Date: Message-ID; i=@hostbrook.com; s=220409; t=1649563196; c=relaxed/relaxed; b=e7+gyrXDx9S4cLgOTytsC4j5eVWlLHHZYItiH3d2jMOjBVpJBOF8WNTBibh6WqaNmcXu+M9S2 tLDYf7c5xfSowS/3hll2s34fAKU6EXzogtZSd4LV6ph2l1RZRCE2BDJFW6kP+BAAFGv5wVGfB rGIbD9uYZYu+teaSde9l55ApA/uYpkc9EtNNQ03gRNsdcp1XhDLUI8rZDAP6N8RSRHx9v7ed7 QdMIm5Gax4b2XkM5Ko9GI/GNO+3NqadnC+w+TJHE74Z4fqJGycRBd4phY1zfqKZrGZ6aavq29 2vTVq5fDKivK+fEC3LaREFLmqnBDLfcfoDp7wrQe2LJINx/6zw==
Content-Type: multipart/alternative; boundary=YN6_aMme
```

Spam-test from `app.mailgenius.com/spam-test/`:

```
(-2 points) Your email is not properly authenticated with DKIM.
Solution:
Update your DNS records with the correct public DKIM key.
The public key, represented by the p= tag, on your DKIM DNS record is unverified or revoked.

Existing DKIM Signature Header:
Version: 1
Domain: hostbrook.com
Algorithm: rsa-sha256
Algorithm_type: ; d=hostbrook.com
Selector: 220409
```

Spam-test from `mailtrap.io`:

```
DKIM_SIGNED Message has a DKIM or DK signature, not necessarily valid
DKIM_INVALID DKIM or DK signature exists, but is not valid
```

What did I do wrong?
Laravel v9.7.0
Your package, the latest version: 2.0.0
Thank you!

**Comment by simonschaufi** [comment]
I could offer you paid support as the package does its job correctly and without debugging I have no chance to know where the error is. If you accept my offer, you can contact me on my website: https://www.simonschaufelberger.de/de/kontakt.html

**Comment by hostbrook** [comment]
I do not know if you receive my emails via the form provided. Just in case if not, this is what I found. Your package works well and DKIM is valid only in the case if email built either with HTML or PLAIN TEXT template. In my case, all my emails have both HTML and PLAIN TEXT, because this is a good practice. For example, how I build a message:
```
class ContactForm extends Mailable
{
    ...

    public function build()
    {
        $this->subject($this->mailData['subject'])
            ->view('mail.contact-form_html')
            ->text('mail.contact-form_plain');
        return $this;
    }
}
```
So, if you use both templates to build the email (what is the right way) you get an invalid DKIM signature. Actually, SWIFT mailer at Laravel 8 didn't have this issue.

Next, I have dug this issue with Symfony mailer and found the possible way on how to fix it, here:
[https://github.com/symfony/symfony/issues/39354#issuecomment-894379296](https://github.com/symfony/symfony/issues/39354#issuecomment-894379296)

Please double-check it.

**Comment by simonschaufi** [comment]
Ok then this is really a bug.

**Comment by hostbrook** [comment]
I do not think this is a bug in your package, probably this is the issue at Symfony Mailer. But curious if you can bypass it in your package somehow. Anyways, please double-check before closing the issue. Thanks!

**Comment by simonschaufi** [comment]
@fjahn I would prefer a pull request instead of some code snippets here.

**Comment by fjahn** [comment]
Sorry for that! The code is untested, I just thought that since I dug the source code already, it would be a waste not to suggest these hotfixes for others. I would not recommend doing this, this is just if you desparately need to fix DKIM right now and don't care about compatibility.

Having said that, I will submit a PR nontheless, but I want to point out that this is a severe breaking change that modifies existing behavior of Symphony Mailer.

**Comment by simonschaufi** [comment]
Fixed in Symfony
