### ISSUE TITLE
No private key set

### ISSUE THREAD

**Issue by bardolf69** [simonschaufi/laravel-dkim#14]
Thanks for your hard work on this package.  I have seen the previous issue with the same problem and followed through with all the steps listed in it, but I still have the same issue.  The private_key.txt file is in the default path but I also tried putting the full path in the .env file (DKIM_PRIVATE_KEY=/var/www/??????/storage/app/dkim/private_key.txt) and refreshed the config with no change in behavior.  The only thing I can think of is there is a problem with the file itself.  I have tried it both with and without BEGIN and END RSA tags.

**Comment by bardolf69** [comment]
yeah, I did generate the key with that page.

**Comment by simonschaufi** [comment]
I'm closing this issue as it seams either the key is wrong or the path is wrong.
