### ISSUE TITLE
Error with ShouldQueue

### ISSUE THREAD

**Issue by Arnwaltur** [simonschaufi/laravel-dkim#24]
Hello,

With Laravel 10.x, I use it without any problem laravel-dkim, but if I try to send the mail in a queue I get an error message (but the mail goes anyway).

```
use Illuminate\Contracts\Queue\ShouldQueue;
 
class OrderShipped extends Mailable implements ShouldQueue
{
    // ...
}
```

Error message :
`SimonSchaufi\LaravelDKIM\Mailer::send(): Return value must be of type ?Illuminate\Mail\SentMessage, string returned`

From : vendor / simonschaufi / laravel-dkim / src / Mailer.php : 25
`return $this->sendMailable($view);`

How can I get rid of the error (it's driving me crazy)?

Thanks for your work, I appreciate it.

**Comment by simonschaufi** [comment]
Hi, could you debug this please for me and tell me what exactly is the return value in this case? I'm just overwriting a method and the doctype says that it returns `SentMessage|null` which is not true in this case. I guess this is a Laravel framework bug.
