### ISSUE TITLE
No private key set

### ISSUE THREAD

**Issue by Justproof** [simonschaufi/laravel-dkim#8]
Hey, Simon. Thanks for creating this package. Perhaps I'm missing something on the final setup because the app isn't locating my private_key.txt?

Laravel Log: `production.ERROR: No private key set. {"exception":"[object] (SimonSchaufi\\LaravelDKIM\\Exception\\MissingConfigurationException(code: 1588115551): No private key set.`

I followed the documentation on storing the private_key.txt and referencing the absolute path in the .env, however, I'm not sure why this doesn't seem to grab the private key. I also tried updating and clearing the composer cache.

DKIM_PRIVATE_KEY=storage_path('/home/mydomain.com/app/dkim/private_key.txt')

Thanks for the help!

**Comment by simonschaufi** [comment]
Hi Russell, you cannot put php code in the env file. This is plan text only. In that case you need to put the absolute path in that file or as I mentioned, adjust the configuration file that should be copied over to your app and forget about the .env value. I hope you understood what I mean.

**Comment by Justproof** [comment]
Thanks, Simon. I appreciate the info. 
I added the absolute path to the private key in this config file >> vendor/simonschaufi/laravel-dkim/config/dkim.php and removed the values from the .env file.

I believe I'm getting close, but I have the same "No private key set"
'private_key' => storage_path('/home/pcdrama/app/dkim/private_key.txt'),

**Comment by simonschaufi** [comment]
Either set:

```
DKIM_PRIVATE_KEY=/home/mydomain.com/app/dkim/private_key.txt
```
in your `.env` or
```
'private_key' => storage_path('app/dkim/private_key.txt'),
```
in your config file but never change any file in `vendor`! You need to copy the config file your your own config folder.

**Comment by Justproof** [comment]
got it. Thanks!
