### ISSUE TITLE
Laravel 9 compatibility

### ISSUE THREAD

**Issue by curious-mike-dvc** [simonschaufi/laravel-dkim#9]
Hi, is it possible to publish a release compatible with Laravel 9 ?

>  - Root composer.json requires simonschaufi/laravel-dkim ^1.1 -> satisfiable by simonschaufi/laravel-dkim[v1.1.0].
    - simonschaufi/laravel-dkim v1.1.0 requires illuminate/mail ^7.0 || ^8.0 -> found illuminate/mail[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by simonschaufi** [comment]
Sure, I can do that. I'm glad to hear that you use my package. Maybe it's just to adjust the composer dependency, but I still need to run some tests to make sure it works, and that takes a bit of time. Would you sponsor me with a little tip for that? I would highly appreciate that. You can do that either via GitHub Sponsor button or via the PayPal link on the sponsor button.
